SELECT CUSTOMERS.CUSTOMER_NAME AS 'Customer', PRINTF('$%.2f', SUM(SUBSCRIPTIONS.PRICE_PER_MONTH * SUBSCRIPTIONS.SUBSCRIPTION_LENGTH)) AS 'Amount Due'
FROM ORDERS
INNER JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
INNER JOIN SUBSCRIPTIONS ON ORDERS.SUBSCRIPTION_ID = SUBSCRIPTIONS.SUBSCRIPTION_ID
WHERE ORDERS.ORDER_STATUS = 'unpaid' AND SUBSCRIPTIONS.DESCRIPTION ='Fashion Magazine'
GROUP BY CUSTOMERS.CUSTOMER_NAME